#!/bin/bash

# Script for automating an Arch Linux installation
# Assumes that you've already done a base install

# base packages to install (basic dependencies, xorg, text-editor, etc.)
base_packages=(
	"git"
	"neovim"
	"firefox"
	"libx11"
	"libxft"
	"xorg-server"
	"xorg-xinit"
	"terminus-font"
)

packages=(
	"tmux"
	"htop"
	"neofetch"
)

dotfiles="https://github.com/mCaballero1224/dotfiles.git"




git_repos=(
	"https://
)

# Update/synchronize the system
$(which echo) "Updating system..."
sudo pacman -Syu

# Set locale

# Set timezone

# Install base packages
$(which echo) "Installing base packages..."

for i in "${!base_packages[@]}"
do
	sudo pacman -S $(base_packages[i])
done

# Create primary user
read -p "Enter username for primary user: " username
read -p "Enter password for '${username}': " user_pass
$(which echo) "Creating user '${username}'..."

# Give primary user admin priveleges
$(which echo) "useradd -m -G storage,power,video,wheel ${username} -p {user_pass} -s /bin/bash"

# Download dotfiles
$(which git) clone $(dotfiles)

# Download git repos 
for i in "${!git_repos[@]}"
do
	$(which git) clone $(git_repo[i])
done
