#!/bin/bash

# Define the tmux session name
STATUS_SESSION="status"

# Check if the session already exists
if ! tmux has-session -t $STATUS_SESSION 2>/dev/null; then
	# Start a new tmux session
	tmux new-session -d -s $STATUS_SESSION

	# Split the window into multiple panes
	tmux split-window -h
	tmux split-window -v

	# Select the first pane and send a command
	tmux select-pan -t 0
	tmux send-keys 'calcurse' C-m

	# Select the second pane and send a command
	tmux select-pan -t 1
	tmux send-keys 'htop' C-m

	# Select the third pane and send a command
	# tmux select-pan -t 2
	# tmux send-keys 'nvim .' C-m

	# Attach to the tmux session
	tmux attach -t $STATUS_SESSION
else 
	tmux attach -t $STATUS_SESSION
fi
